/auth/local:
  x-swagger-router-controller: local.controller
# callback
  post:
    operationId: callback
    tags:
      - Authentication
    summary: Signin
    description: |
    Login
    username=string password=string
    consumes:
    - application/json
    parameters:
    - in: body
    name: body
    required: true
    schema:
       $ref: '#/definitions/User'
    responses:
      200:
        description: Success.
        schema:
            type: object
            properties:
              token:
                type: string
      422:
        $ref: '#/responses/auth-422'
      500:
        $ref: '#/responses/auth-500'
